name: Deploy Azure Container App

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: rg-containerapp-001
      LOCATION: centralus

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Resource Group
        run: |
          az group create \
            --name $RESOURCE_GROUP \
            --location $LOCATION

      - name: Validate Bicep Template
        run: |
          az deployment group validate \
            --resource-group $RESOURCE_GROUP \
            --template-file main.bicep \
            --parameters \
              aadClientId="${{ secrets.AAD_CLIENT_ID }}" \
              aadTenantId="${{ secrets.AAD_TENANT_ID }}"

      - name: What If Deployment
        run: |
          az deployment group what-if \
            --resource-group $RESOURCE_GROUP \
            --template-file main.bicep \
            --parameters \
              aadClientId="${{ secrets.AAD_CLIENT_ID }}" \
              aadTenantId="${{ secrets.AAD_TENANT_ID }}"

      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --template-file main.bicep \
            --parameters \
              aadClientId="${{ secrets.AAD_CLIENT_ID }}" \
              aadTenantId="${{ secrets.AAD_TENANT_ID }}"

      - name: Get Container App URL
        id: appurl
        run: |
          FQDN=$(az containerapp show \
            --name hello-world \
            --resource-group $RESOURCE_GROUP \
            --query properties.configuration.ingress.fqdn \
            -o tsv)

          echo "fqdn=$FQDN" >> $GITHUB_OUTPUT

      - name: Display Authentication Callback URL
        run: |
          echo "Add this Redirect URI to hello-world-appregis:"
          echo "https://${{ steps.appurl.outputs.fqdn }}/.auth/login/aad/callback"

      - name: Verify Deployment
        run: |
          az containerapp show \
            --name hello-world \
            --resource-group $RESOURCE_GROUP \
            --output table
